FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --production

COPY frontend ./frontend

WORKDIR /app/frontend
RUN npm run build

FROM nginx:stable-alpine
COPY --from=0 /app/frontend/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
